# Swift lint configuration file

disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - fallthrough
  - for_where
  - nesting
  - redundant_optional_initialization
  - todo
  - trailing_comma
  - function_parameter_count

opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - closure_body_length
  - closure_end_indentation
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - no_extension_access_modifier
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prohibited_interface_builder
  - prohibited_super_call
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_whitespace
  - unavailable_function
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 80
  error: 120

closure_body_length:
  warning: 30
  error: 100

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

file_length:
  warning: 600
  error: 1200

number_separator:
  minimum_length: 7
  minimum_fraction_length: 6

vertical_whitespace:
  max_empty_lines: 3

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 80
  excluded:
    - UI
    - Key
    - ID
    - Red
    - Bar
    - Map

identifier_name:
  excluded:
    - id
    - to
    - ui
    - x
    - y
    - z
    - i
    - up
  allowed_symbols: "_"

modifier_order:
  preferred_modifier_order:
    - acl
    - override

force_unwrapping:
  severity: error

custom_rules:
  # Enforce space after // in single line comments
  # "// Comment text" => good
  # "//Comment text" => bad
  space_comments:
    name: "Single line comment space"
    match_kinds:
      comment
    message: "There must be space before text in single line comments"
    regex: "(^//\\S)"
